version: '3'
services:
  manager-nginx:
    image: ${REGISTRY_ADDRESS}/projector-nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - projector-php-fpm
    ports:
      - "80:80"
  projector-php-fpm:
    image: ${REGISTRY_ADDRESS}/projector-php-fpm:${IMAGE_TAG}
    restart: always
  projector-php-cli:
    image: ${REGISTRY_ADDRESS}/projector-php-cli:${IMAGE_TAG}
